apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-indexer
  namespace: crossbell
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: bridge
      tier: indexer
  template:
    metadata:
      labels:
        app: bridge
        tier: indexer
    spec:
      containers:
        - image: $IMAGE_TAG_RELEASE
          imagePullPolicy: Always
          name: bridge-indexer
          env:
            - name: CONFIG_PATH
              value: /opt/bridge/config/config.indexer.json
            - name: VERBOSITY
              value: "1"
          command:
            - bridge
            - --config
            - /opt/bridge/config/config.indexer.json
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "200m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: "/opt/bridge/config/"
              name: bridge-indexer
              readOnly: true
      volumes:
      - name: bridge-indexer
        secret:
          secretName: bridge-indexer
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
