apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy-validator-01.yaml
  - deploy-validator-02.yaml
  - deploy.yaml
  - sa.yaml
  - secrets.yaml
  - validator_secrets.yaml

replicas:
  - name: bridge-indexer
    count: 0
  - name: bridge-validator-01
    count: 0
  - name: bridge-validator-02
    count: 0
