apiVersion: v1
stringData:
  config.indexer.json: |
    {
      "listeners": {
        "Crossbell": {
          "chainId": "0xAA36A7",
          "rpcUrl": "$RPC_CSB_DEV",
          "blockTime": 6,
          "safeBlockRange": 8,
          "maxTasksQuery": 1000,
          "minTasksQuery": 50,
          "taskInterval": 15,
          "transactionCheckPeriod": 4,
          "secret": {
            "validator": {
              "plainPrivateKey": ""
            }
          },
          "fromHeight": 2692881,
          "contracts": {
            "CrossbellGateway": "0x335ba596B0C8B0eDE2002b357df67775D82B0C3A"
          },
          "subscriptions": {
            "WithdrawalRequestedSubscription": {
              "to": "0x335ba596B0C8B0eDE2002b357df67775D82B0C3A",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "RequestWithdrawal"
              }
            },
            "RequestWithdrawalSubscription": {
              "to": "0x335ba596B0C8B0eDE2002b357df67775D82B0C3A",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "RequestWithdrawal"
              },
              "callbacks": {
                "Crossbell": "StoreRequestWithdrawal"
              }
            },
            "DepositedSubscription": {
              "to": "0x335ba596B0C8B0eDE2002b357df67775D82B0C3A",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "Deposited"
              },
              "callbacks": {
                "Crossbell": "StoreCrossbellDepositedCallback"
              }
            },
            "SubmitSignaturesSubscription": {
              "to": "0x335ba596B0C8B0eDE2002b357df67775D82B0C3A",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "SubmitWithdrawalSignatures"
              },
              "callbacks": {
                "Crossbell": "StoreBatchSubmitWithdrawalSignatures"
              }
            },
            "AckDepositSubscription": {
              "to": "0x335ba596B0C8B0eDE2002b357df67775D82B0C3A",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "AckDeposit"
              },
              "callbacks": {
                "Crossbell": "StoreDepositAck"
              }
            }
          }
        },
        "Ethereum": {
          "disabled": false,
          "chainId": "0x5",
          "domainSeperator": "0xeb2a4fb584d0612bfba58fd063e643a30b6a38f81cc096aab2b508f45997002f",
          "rpcUrl": "$RPC_ETH_DEV",
          "blockTime": 4,
          "safeBlockRange": 8,
          "transactionCheckPeriod": 4,
          "secret": {
              "validator": {
                "plainPrivateKey": ""
              }
          },
          "fromHeight": 8321857,
          "contracts": {
            "MainchainGateway": "0x462074b85c3bD27721FaF01be6600D5d7Bf49A7c"
          },
          "subscriptions": {
            "DepositRequestedSubscription": {
              "to": "0x462074b85c3bD27721FaF01be6600D5d7Bf49A7c",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "RequestDeposit"
              },
              "callbacks": {
                "Crossbell": "StoreRequestDeposit"
              }
            },
            "WithdrewSubscription": {
              "to": "0x462074b85c3bD27721FaF01be6600D5d7Bf49A7c",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "Withdrew"
              },
              "callbacks": {
                "Crossbell": "StoreMainchainWithdrewCallback"
              }
            }
          }
        }
      },
      "database": {
        "host": "$DB_HOST_DEV",
        "user": "$DB_USER_DEV",
        "password": "$DB_PASS_DEV",
        "dbName": "relayer",
        "port": 5432,
        "maxOpenConns": 50
      }
    }
kind: Secret
metadata:
  name: bridge-indexer
  namespace: crossbell
type: Opaque
