apiVersion: v1
stringData:
  config.indexer.json: |
    {
      "listeners": {
        "Crossbell": {
          "chainId": "0xAA36A7",
          "rpcUrl": "<RPC_CSB>",
          "slackUrl": "<CSB_SLACK_URL>",
          "domainSeparators": {
            "5": "",
            "80001": "",
            "97": ""
          },
          "decimals": {
            "5": 6,
            "80001": 18,
            "97": 18
          },
          "blockTime": 10,
          "safeBlockRange": 6,
          "preventOmissionRange": 0,
          "maxTasksQuery": 1000,
          "minTasksQuery": 50,
          "taskInterval": 15,
          "transactionCheckPeriod": 15,
          "secret": {
            "validator": {
              "plainPrivateKey": ""
            }
          },
          "fromHeight": 2904605,
          "contracts": {
            "CrossbellGateway": "0x3C247725af72732Cd85267F2ff62C9092201eAAD"
          },
          "subscriptions": {
            "WithdrawalRequestedSubscription": {
              "to": "0x3C247725af72732Cd85267F2ff62C9092201eAAD",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "RequestWithdrawal"
              }
            },
            "StoreRequestWithdrawalSubscription": {
              "to": "0x3C247725af72732Cd85267F2ff62C9092201eAAD",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "RequestWithdrawal"
              },
              "callbacks": {
                "Crossbell": "StoreRequestWithdrawal"
              }
            },
            "DepositedSubscription": {
              "to": "0x3C247725af72732Cd85267F2ff62C9092201eAAD",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "Deposited"
              },
              "callbacks": {
                "Crossbell": "StoreCrossbellDepositedCallback"
              }
            },
            "DepositedDoneSubscription": {
              "to": "0x3C247725af72732Cd85267F2ff62C9092201eAAD",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "Deposited"
              },
              "callbacks": {
                "Crossbell": "RequestDepositedDoneCallback"
              }
            },
            "SubmitSignaturesSubscription": {
              "to": "0x3C247725af72732Cd85267F2ff62C9092201eAAD",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "SubmitWithdrawalSignatures"
              },
              "callbacks": {
                "Crossbell": "StoreBatchSubmitWithdrawalSignatures"
              }
            },
            "AckDepositSubscription": {
              "to": "0x3C247725af72732Cd85267F2ff62C9092201eAAD",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "AckDeposit"
              },
              "callbacks": {
                "Crossbell": "StoreDepositAck"
              }
            }
          }
        },
        "Ethereum": {
          "disabled": false,
          "chainId": "0x5",
          "rpcUrl": "<RPC_ETH>",
          "slackUrl": "<CSB_SLACK_URL>",
          "blockTime": 10,
          "safeBlockRange": 6,
          "preventOmissionRange": 0,
          "transactionCheckPeriod": 15,
          "secret": {
              "validator": {
                "plainPrivateKey": ""
              }
          },
          "fromHeight": 8494817,
          "contracts": {
            "MainchainGateway": "0x86209ccEBe4A7aF99c39c4C2dC806a2983Ef4BaC"
          },
          "subscriptions": {
            "DepositRequestedSubscription": {
              "to": "0x86209ccEBe4A7aF99c39c4C2dC806a2983Ef4BaC",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "RequestDeposit"
              }
            },
            "StoreDepositRequestedSubscription": {
              "to": "0x86209ccEBe4A7aF99c39c4C2dC806a2983Ef4BaC",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "RequestDeposit"
              },
              "callbacks": {
                "Crossbell": "StoreRequestDeposit"
              }
            },
            "RequestWithdrewDoneSubscription": {
              "to": "0x86209ccEBe4A7aF99c39c4C2dC806a2983Ef4BaC",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "Withdrew"
              },
              "callbacks": {
                "Crossbell": "RequestWithdrewDoneCallback",
                "Ethereum": "WithdrewDone2SlackCallback"
              }
            }
          }
        },
        "Polygon": {
          "disabled": false,
          "chainId": "0x13881",
          "rpcUrl": "<RPC_POLYGON>",
          "slackUrl": "<CSB_SLACK_URL>",
          "blockTime": 4,
          "safeBlockRange": 8,
          "preventOmissionRange": 0,
          "transactionCheckPeriod": 15,
          "secret": {
              "validator": {
                "plainPrivateKey": ""
              }
          },
          "fromHeight": 32064671,
          "contracts": {
            "MainchainGateway": "0x994BDa5Dbd28C4016F2e2C731D4AEb874C23Fe25"
          },
          "subscriptions": {
            "DepositRequestedSubscription": {
              "to": "0x994BDa5Dbd28C4016F2e2C731D4AEb874C23Fe25",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "RequestDeposit"
              }
            },
            "StoreDepositRequestedSubscription": {
              "to": "0x994BDa5Dbd28C4016F2e2C731D4AEb874C23Fe25",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "RequestDeposit"
              },
              "callbacks": {
                "Crossbell": "StoreRequestDeposit"
              }
            },
            "RequestWithdrewDoneSubscription": {
              "to": "0x994BDa5Dbd28C4016F2e2C731D4AEb874C23Fe25",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "Withdrew"
              },
              "callbacks": {
                "Crossbell": "RequestWithdrewDoneCallback",
                "Polygon": "WithdrewDone2SlackCallback"
              }
            }
          }
        }
      },
      "database": {
        "host": "<DB_HOST>",
        "user": "<DB_USER>",
        "password": "<DB_PASS>",
        "dbName": "relayer",
        "port": 5432,
        "maxOpenConns": 50
      }
    }
kind: Secret
metadata:
  name: bridge-indexer
  namespace: crossbell
  annotations:
    avp.kubernetes.io/path: "kv/data/crossbell/bridge"
type: Opaque
