apiVersion: v1
stringData:
  config.indexer.json: |
    {
      "listeners": {
        "Crossbell": {
          "chainId": "0xAA36A7",
          "rpcUrl": "$RPC_CSB_DEV",
          "domainSeparators": {
            "5": "0xf1188e940b30a4779b7b68d9fcfcf5f83071392de7f36aeb423a3f78c2671e6c",
            "80001": "",
            "97": ""
          },
          "blockTime": 6,
          "safeBlockRange": 8,
          "maxTasksQuery": 1000,
          "minTasksQuery": 50,
          "taskInterval": 15,
          "transactionCheckPeriod": 4,
          "secret": {
            "validator": {
              "plainPrivateKey": ""
            }
          },
          "fromHeight": 2783541,
          "contracts": {
            "CrossbellGateway": "0x3C247725af72732Cd85267F2ff62C9092201eAAD"
          },
          "subscriptions": {
            "WithdrawalRequestedSubscription": {
              "to": "0x3C247725af72732Cd85267F2ff62C9092201eAAD",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "RequestWithdrawal"
              }
            },
            "RequestWithdrawalSubscription": {
              "to": "0x3C247725af72732Cd85267F2ff62C9092201eAAD",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "RequestWithdrawal"
              },
              "callbacks": {
                "Crossbell": "StoreRequestWithdrawal"
              }
            },
            "DepositedSubscription": {
              "to": "0x3C247725af72732Cd85267F2ff62C9092201eAAD",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "Deposited"
              },
              "callbacks": {
                "Crossbell": "StoreCrossbellDepositedCallback"
              }
            },
            "SubmitSignaturesSubscription": {
              "to": "0x3C247725af72732Cd85267F2ff62C9092201eAAD",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "SubmitWithdrawalSignatures"
              },
              "callbacks": {
                "Crossbell": "StoreBatchSubmitWithdrawalSignatures"
              }
            },
            "AckDepositSubscription": {
              "to": "0x3C247725af72732Cd85267F2ff62C9092201eAAD",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "AckDeposit"
              },
              "callbacks": {
                "Crossbell": "StoreDepositAck"
              }
            }
          }
        },
        "Ethereum": {
          "disabled": false,
          "chainId": "0x5",
          "rpcUrl": "$RPC_ETH_DEV",
          "blockTime": 4,
          "safeBlockRange": 8,
          "transactionCheckPeriod": 4,
          "secret": {
              "validator": {
                "plainPrivateKey": ""
              }
          },
          "fromHeight": 8389430,
          "contracts": {
            "MainchainGateway": "0x86209ccEBe4A7aF99c39c4C2dC806a2983Ef4BaC"
          },
          "subscriptions": {
            "DepositRequestedSubscription": {
              "to": "0x86209ccEBe4A7aF99c39c4C2dC806a2983Ef4BaC",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "RequestDeposit"
              },
              "callbacks": {
                "Crossbell": "StoreRequestDeposit"
              }
            },
            "WithdrewSubscription": {
              "to": "0x86209ccEBe4A7aF99c39c4C2dC806a2983Ef4BaC",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "Withdrew"
              },
              "callbacks": {
                "Crossbell": "StoreMainchainWithdrewCallback"
              }
            }
          }
        }
      },
      "database": {
        "host": "$DB_HOST_DEV",
        "user": "$DB_USER_DEV",
        "password": "$DB_PASS_DEV",
        "dbName": "relayer",
        "port": 5432,
        "maxOpenConns": 50
      }
    }
kind: Secret
metadata:
  name: bridge-indexer
  namespace: crossbell
type: Opaque
