apiVersion: v1
stringData:
  config.validator01.json: |
    {
      "listeners": {
        "Crossbell": {
          "chainId": "0xAA36A7",
          "rpcUrl": "<RPC_CSB>",
          "domainSeparators": {
            "5": "0xf1188e940b30a4779b7b68d9fcfcf5f83071392de7f36aeb423a3f78c2671e6c",
            "80001": "0xd9de32e281647f6a96f9eb6bb62f2f5f02aa70c8f30ff4610864617c58508a85",
            "97": ""
          },
          "blockTime": 10,
          "safeBlockRange": 6,
          "preventOmissionRange": 0,
          "maxTasksQuery": 1000,
          "minTasksQuery": 50,
          "taskInterval": 15,
          "transactionCheckPeriod": 15,
          "secret": {
            "validator": {
              "keystoreConfig": {
                "keystorePath": "/opt/keystore/keystoreValidator01",
                "password": "<KEY_OF_0XBCD3A0F90C0DF85EF175934F5879CCD920866D54>"
              }
            }
          },
          "fromHeight": 2904605,
          "contracts": {
            "CrossbellGateway": "0x3C247725af72732Cd85267F2ff62C9092201eAAD"
          },
          "subscriptions": {
            "WithdrawalRequestedSubscription": {
              "to": "0x3C247725af72732Cd85267F2ff62C9092201eAAD",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "RequestWithdrawal"
              },
              "callbacks": {
                "Crossbell": "ProvideReceiptSignatureCallback"
              }
            }
          }
        },
        "Ethereum": {
          "disabled": false,
          "chainId": "0x5",
          "rpcUrl": "<RPC_ETH>",
          "blockTime": 10,
          "safeBlockRange": 6,
          "preventOmissionRange": 0,
          "transactionCheckPeriod": 15,
          "secret": {
            "validator": {
              "plainPrivateKey": ""
            }
          },
          "fromHeight": 8494817,
          "contracts": {
            "MainchainGateway": "0x86209ccEBe4A7aF99c39c4C2dC806a2983Ef4BaC"
          },
          "subscriptions": {
            "DepositRequestedSubscription": {
              "to": "0x86209ccEBe4A7aF99c39c4C2dC806a2983Ef4BaC",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "RequestDeposit"
              },
              "callbacks": {
                "Crossbell": "DepositRequestedCallback"
              }
            }
          }
        },
        "Polygon": {
          "disabled": false,
          "chainId": "0x13881",
          "rpcUrl": "<RPC_POLYGON>",
          "blockTime": 4,
          "safeBlockRange": 8,
          "preventOmissionRange": 0,
          "transactionCheckPeriod": 15,
          "secret": {
            "validator": {
              "plainPrivateKey": ""
            }
          },
          "fromHeight": 32064671,
          "contracts": {
            "MainchainGateway": "0x994BDa5Dbd28C4016F2e2C731D4AEb874C23Fe25"
          },
          "subscriptions": {
            "DepositRequestedSubscription": {
              "to": "0x994BDa5Dbd28C4016F2e2C731D4AEb874C23Fe25",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "RequestDeposit"
              },
              "callbacks": {
                "Crossbell": "DepositRequestedCallback"
              }
            }
          }
        }
      },
      "database": {
        "host": "<DB_HOST>",
        "user": "<DB_USER>",
        "password": "<DB_PASS>",
        "dbName": "validator1",
        "port": 5432,
        "maxOpenConns": 50
      }
    }
  config.validator02.json: |
    {
      "listeners": {
        "Crossbell": {
          "chainId": "0xAA36A7",
          "rpcUrl": "<RPC_CSB>",
          "domainSeparators": {
            "5": "0xf1188e940b30a4779b7b68d9fcfcf5f83071392de7f36aeb423a3f78c2671e6c",
            "80001": "0xd9de32e281647f6a96f9eb6bb62f2f5f02aa70c8f30ff4610864617c58508a85",
            "97": ""
          },
          "blockTime": 10,
          "safeBlockRange": 6,
          "preventOmissionRange": 0,
          "maxTasksQuery": 1000,
          "minTasksQuery": 50,
          "taskInterval": 15,
          "transactionCheckPeriod": 15,
          "secret": {
            "validator": {
              "keystoreConfig": {
                "keystorePath": "/opt/keystore/keystoreValidator02",
                "password": "<KEY_OF_0X68FCDBFF9A2DBD78B6D06057DF6DCBF6C894D17F>"
              }
            }
          },
          "fromHeight": 2904605,
          "contracts": {
            "CrossbellGateway": "0x3C247725af72732Cd85267F2ff62C9092201eAAD"
          },
          "subscriptions": {
            "WithdrawalRequestedSubscription": {
              "to": "0x3C247725af72732Cd85267F2ff62C9092201eAAD",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "RequestWithdrawal"
              },
              "callbacks": {
                "Crossbell": "ProvideReceiptSignatureCallback"
              }
            }
          }
        },
        "Ethereum": {
          "disabled": false,
          "chainId": "0x5",
          "rpcUrl": "<RPC_ETH>",
          "blockTime": 10,
          "safeBlockRange": 6,
          "preventOmissionRange": 0,
          "transactionCheckPeriod": 15,
          "secret": {
            "validator": {
              "plainPrivateKey": ""
            }
          },
          "fromHeight": 8494817,
          "contracts": {
            "MainchainGateway": "0x86209ccEBe4A7aF99c39c4C2dC806a2983Ef4BaC"
          },
          "subscriptions": {
            "DepositRequestedSubscription": {
              "to": "0x86209ccEBe4A7aF99c39c4C2dC806a2983Ef4BaC",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "RequestDeposit"
              },
              "callbacks": {
                "Crossbell": "DepositRequestedCallback"
              }
            }
          }
        },
        "Polygon": {
          "disabled": false,
          "chainId": "0x13881",
          "rpcUrl": "<RPC_POLYGON>",
          "blockTime": 4,
          "safeBlockRange": 8,
          "preventOmissionRange": 0,
          "transactionCheckPeriod": 15,
          "secret": {
            "validator": {
              "plainPrivateKey": ""
            }
          },
          "fromHeight": 32064671,
          "contracts": {
            "MainchainGateway": "0x994BDa5Dbd28C4016F2e2C731D4AEb874C23Fe25"
          },
          "subscriptions": {
            "DepositRequestedSubscription": {
              "to": "0x994BDa5Dbd28C4016F2e2C731D4AEb874C23Fe25",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "RequestDeposit"
              },
              "callbacks": {
                "Crossbell": "DepositRequestedCallback"
              }
            }
          }
        }
      },
      "database": {
        "host": "<DB_HOST>",
        "user": "<DB_USER>",
        "password": "<DB_PASS>",
        "dbName": "validator2",
        "port": 5432,
        "maxOpenConns": 50
      }
    }
kind: Secret
metadata:
  name: bridge-validator
  namespace: crossbell
type: Opaque
