apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy-validator-01.yaml
  - deploy-validator-02.yaml
  - deploy.yaml
  - sa.yaml
  - secrets.yaml
  - validator_secrets.yaml
