apiVersion: v1
stringData:
  config.indexer.json: |
    {
      "listeners": {
        "Crossbell": {
          "chainId": "0xE99",
          "name": "Crossbell",
          "rpcUrl": "$RPC_CSB",
          "slackUrl": "$CSB_SLACK_URL",
          "scanUrl": "https://scan.crossbell.io/tx/",
          "domainSeparators": {
            "3737": "",
            "137": ""
          },
          "decimals": {
            "3737": 18,
            "137": 18
          },
          "blockTime": 1,
          "safeBlockRange": 30,
          "preventOmissionRange": 0,
          "maxTasksQuery": 1000,
          "minTasksQuery": 50,
          "taskInterval": 15,
          "transactionCheckPeriod": 15,
          "secret": {
            "validator": {
              "plainPrivateKey": ""
            }
          },
          "fromHeight": 25469431,
          "contracts": {
            "CrossbellGateway": "0x37b0CD884785320d8d2354c7Ae424b32391D50aA"
          },
          "subscriptions": {
            "StoreRequestWithdrawalSubscription": {
              "to": "0x37b0CD884785320d8d2354c7Ae424b32391D50aA",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "RequestWithdrawal"
              },
              "callbacks": {
                "Crossbell": "StoreRequestWithdrawal"
              }
            },
            "DepositedSubscription": {
              "to": "0x37b0CD884785320d8d2354c7Ae424b32391D50aA",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "Deposited"
              },
              "callbacks": {
                "Crossbell": "StoreCrossbellDepositedCallback"
              }
            },
            "DepositedDoneSubscription": {
              "to": "0x37b0CD884785320d8d2354c7Ae424b32391D50aA",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "Deposited"
              },
              "callbacks": {
                "Crossbell": "RequestDepositedDoneCallback"
              }
            },
            "SubmitSignaturesSubscription": {
              "to": "0x37b0CD884785320d8d2354c7Ae424b32391D50aA",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "SubmitWithdrawalSignatures"
              },
              "callbacks": {
                "Crossbell": "StoreBatchSubmitWithdrawalSignatures"
              }
            },
            "AckDepositSubscription": {
              "to": "0x37b0CD884785320d8d2354c7Ae424b32391D50aA",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "AckDeposit"
              },
              "callbacks": {
                "Crossbell": "StoreDepositAck"
              }
            }
          }
        },
        "Polygon": {
          "disabled": false,
          "chainId": "0x89",
          "name": "Polygon",
          "rpcUrl": "$RPC_POLYGON",
          "slackUrl": "$CSB_SLACK_URL",
          "scanUrl": "https://polygonscan.com/tx/",
          "decimals": {
            "3737": 18,
            "137": 18
          },
          "blockTime": 2,
          "safeBlockRange": 300,
          "preventOmissionRange": 0,
          "transactionCheckPeriod": 15,
          "secret": {
              "validator": {
                "plainPrivateKey": ""
              }
          },
          "fromHeight": 40027744,
          "contracts": {
            "MainchainGateway": "0x901F109c602D2D1f4c1B4a7236113CE090A4292a"
          },
          "subscriptions": {
            "DepositRequestedSubscription": {
              "to": "0x901F109c602D2D1f4c1B4a7236113CE090A4292a",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "RequestDeposit"
              }
            },
            "StoreDepositRequestedSubscription": {
              "to": "0x901F109c602D2D1f4c1B4a7236113CE090A4292a",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "RequestDeposit"
              },
              "callbacks": {
                "Crossbell": "StoreRequestDeposit"
              }
            },
            "RequestWithdrewDoneSubscription": {
              "to": "0x901F109c602D2D1f4c1B4a7236113CE090A4292a",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "Withdrew"
              },
              "callbacks": {
                "Crossbell": "RequestWithdrewDoneCallback",
                "Polygon": "WithdrewDone2SlackCallback"
              }
            }
          }
        }
      },
      "database": {
        "host": "$DB_HOST",
        "user": "$DB_USER",
        "password": "$DB_PASS",
        "dbName": "relayer",
        "port": 5432,
        "maxOpenConns": 50
      }
    }
kind: Secret
metadata:
  name: bridge-indexer
  namespace: crossbell
type: Opaque
