apiVersion: v1
stringData:
  config.validator01.json: |
    {
      "listeners": {
        "Crossbell": {
          "chainId": "0xE99",
          "rpcUrl": "$RPC_CSB",
          "domainSeparators": {
            "137": "0xa3a31461158a3cea2e85b0d67c16d2d751e8e653265117982f29ee3fdaf8c283"
          },
          "blockTime": 1,
          "safeBlockRange": 30,
          "preventOmissionRange": 0,
          "maxTasksQuery": 1000,
          "minTasksQuery": 50,
          "taskInterval": 15,
          "transactionCheckPeriod": 15,
          "secret": {
            "validator": {
              "keystoreConfig": {
                "keystorePath": "/opt/keystore/keystoreValidator01",
                "password": "$KEY_OF_0X7d07170538fe11bd793276693ec92edb80680ea8"
              }
            }
          },
          "fromHeight": 25469431,
          "contracts": {
            "CrossbellGateway": "0x37b0CD884785320d8d2354c7Ae424b32391D50aA"
          },
          "subscriptions": {
            "WithdrawalRequestedSubscription": {
              "to": "0x37b0CD884785320d8d2354c7Ae424b32391D50aA",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "RequestWithdrawal"
              },
              "callbacks": {
                "Crossbell": "ProvideReceiptSignatureCallback"
              }
            }
          }
        },
        "Polygon": {
          "disabled": false,
          "chainId": "0x89",
          "rpcUrl": "$RPC_POLYGON",
          "blockTime": 2,
          "safeBlockRange": 300,
          "preventOmissionRange": 0,
          "transactionCheckPeriod": 15,
          "secret": {
            "validator": {
              "plainPrivateKey": ""
            }
          },
          "fromHeight": 40027744,
          "contracts": {
            "MainchainGateway": "0x901F109c602D2D1f4c1B4a7236113CE090A4292a"
          },
          "subscriptions": {
            "DepositRequestedSubscription": {
              "to": "0x901F109c602D2D1f4c1B4a7236113CE090A4292a",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "RequestDeposit"
              },
              "callbacks": {
                "Crossbell": "DepositRequestedCallback"
              }
            }
          }
        }
      },
      "database": {
        "host": "$DB_HOST",
        "user": "$DB_USER",
        "password": "$DB_PASS",
        "dbName": "validator1",
        "port": 5432,
        "maxOpenConns": 50
      }
    }
  config.validator02.json: |
    {
      "listeners": {
        "Crossbell": {
          "chainId": "0xE99",
          "rpcUrl": "$RPC_CSB",
          "domainSeparators": {
            "137": "0xa3a31461158a3cea2e85b0d67c16d2d751e8e653265117982f29ee3fdaf8c283"
          },
          "blockTime": 1,
          "safeBlockRange": 30,
          "preventOmissionRange": 0,
          "maxTasksQuery": 1000,
          "minTasksQuery": 50,
          "taskInterval": 15,
          "transactionCheckPeriod": 15,
          "secret": {
            "validator": {
              "keystoreConfig": {
                "keystorePath": "/opt/keystore/keystoreValidator02",
                "password": "$KEY_OF_0x1b88C522f1A4566e7AFc7D6400DB15F7afe54e59"
              }
            }
          },
          "fromHeight": 25469431,
          "contracts": {
            "CrossbellGateway": "0x37b0CD884785320d8d2354c7Ae424b32391D50aA"
          },
          "subscriptions": {
            "WithdrawalRequestedSubscription": {
              "to": "0x37b0CD884785320d8d2354c7Ae424b32391D50aA",
              "type": 1,
              "handler": {
                "contract": "CrossbellGateway",
                "name": "RequestWithdrawal"
              },
              "callbacks": {
                "Crossbell": "ProvideReceiptSignatureCallback"
              }
            }
          }
        },
        "Polygon": {
          "disabled": false,
          "chainId": "0x89",
          "rpcUrl": "$RPC_POLYGON",
          "blockTime": 2,
          "safeBlockRange": 300,
          "preventOmissionRange": 0,
          "transactionCheckPeriod": 15,
          "secret": {
            "validator": {
              "plainPrivateKey": ""
            }
          },
          "fromHeight": 40027744,
          "contracts": {
            "MainchainGateway": "0x901F109c602D2D1f4c1B4a7236113CE090A4292a"
          },
          "subscriptions": {
            "DepositRequestedSubscription": {
              "to": "0x901F109c602D2D1f4c1B4a7236113CE090A4292a",
              "type": 1,
              "handler": {
                "contract": "MainchainGateway",
                "name": "RequestDeposit"
              },
              "callbacks": {
                "Crossbell": "DepositRequestedCallback"
              }
            }
          }
        }
      },
      "database": {
        "host": "$DB_HOST",
        "user": "$DB_USER",
        "password": "$DB_PASS",
        "dbName": "validator2",
        "port": 5432,
        "maxOpenConns": 50
      }
    }
kind: Secret
metadata:
  name: bridge-validator
  namespace: crossbell
type: Opaque
