name: Build and Deploy
on:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - "deploy/**"
jobs:
  build:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    with:
      images: flosspicks/bridge
      context: .
      dockerfile: ./Dockerfile
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy-dev:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    needs:
      - build
    with:
      images: flosspicks/bridge
      tag: sha-${{ github.sha }}
      cluster: dev
      namespace: crossbell
      releaseName: bridge
      revision: master
      dir: deploy/dev
    secrets:
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
  deploy-prod:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    needs:
      - build
    with:
      images: flosspicks/bridge
      tag: ${{ github.ref_name }}
      cluster: prod
      namespace: crossbell
      releaseName: bridge
      revision: ${{ github.ref_name }}
      dir: deploy/prod
    secrets:
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
