name: Dockerize

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    uses: axieinfinity/workflows-samples/.github/workflows/docker-build-submodule.yml@main
    with:
      checkout_submodules: true
      image_repository: gcr.io/test-servers-256610/bridge-v2
    secrets: inherit
